server:
  port: 9999
  context-path: /tushare
spring:
  profiles:
    active: dev

logging:
  level:
    root: debug
    org.springframework.boot: error
    com.yulaiz.web: debug
  file:
    name: ${catalina.base}/logs/test.log


