database: mysql
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://120.25.205.73:3306/tushare?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: 106.53.212.139
    port: 6379
    password: 123456
  mongdb:
    uri: mongodb://106.53.212.139:27017/tushare
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false

