server:
  port: 9999
  context-path: /spilder

database: mysql
spring:
  datasource:
      username: root
      password: 123456
      url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456

mybatis:
  type-aliases-package: com.yulaiz.web.dao
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: debug
    org.springframework.boot: error
    com.yulaiz.web: debug
  file:
    name: ${catalina.base}/logs/test.log

#爬虫
spilder.gov.pre: https://data.stats.gov.cn/
#定时任务
webmagic.job.cron=0 0 0 1 * ? *

