server:
   port: 8082
   servlet:
     context-path: /demo

spring:
  application:
    name: service
    active:
  redis: #
    host: 106.53.212.139
    password: 123456
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  default-property-inclusion: non_null
  serialization:
    write_dates_as_timestamps: true
  cache:
    redis:
      time-to-live: 86400s
