server:
   port: 8080 # 服务绑定的端口，不写默认是8080
   servlet:
     context-path: /demo # 服务的路径，不写默认为空

spring:
  application:
    name: service #服务名
  profiles:
    active: default # 配置文件的版本
  datasource: # 数据库配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: xyh
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/xyh?useSSL=false&testOnBorrow=true&testWhileIdle=true
  redis: # redis配置
    host: localhost
    password: 123456
    port: 8397
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  jackson:# 关于jackson的配置
  default-property-inclusion: non_null
  serialization:
    write_dates_as_timestamps: true
  cache:
    redis:
      time-to-live: 86400s
